# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric and Minecraft
minecraft_version=1.21.1
loader_version=0.19.1
loom_version=1.7.4
fabric_api_version=0.116.10+1.21.1
jei_version=19.27.0.340

# Mod metadata
mod_id=clickclose
mod_name=Click Close!
mod_license=MIT
mod_version=1.0.1
mod_group_id=net.cama.clickclose
mod_authors=cama
mod_description=Allows closing a container or GUI by clicking outside of the container itself (click the background).
